---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - fivetranconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - fivetranconnectors/finalizers
  verbs:
  - update
- apiGroups:
  - operator.dataverse.redhat.com
  resources:
  - fivetranconnectors/status
  verbs:
  - get
  - patch
  - update
